const configAws = {
  upload: {
    folder_temp: "uploads/temp/",
    folder_upload: "uploads/images/",
    domain_local: "http://18.136.76.42/lime_back/",
    domain_ftp: "/", // Not used in the provided PHP code
    s3_domain: "https://s3.ap-northeast-2.amazonaws.com",
    s3_domain_nodejs: "https://shuket-admin.s3.ap-southeast-2.amazonaws.com", // giang S3
    s3_bucket: "moa.images",
    time_rand: true,
    check_mime: true,
    default_no_img: "no-image.jpg",
    watermark: {
      wm_type: "overlay",
      wm_padding: 10,
      wm_vrt_alignment: "bottom",
      wm_hor_alignment: "right",
      wm_overlay_path: "./themes/general/images/watermark/logo.png",
      wm_hor_offset: 10,
      wm_vrt_offset: 10,
      wm_opacity: 70,
    },
    brand: {
      cover: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "3072",
        min_width: 457,
        min_height: 655,
        pre_name: "br-",
        sub_name: "",
        time_rand: 4,
        servers: {
          sv1: {
            type: "aws",
            using: true,
            s3_key: "",
            s3_bucket: "",
            sub_folder: "brand/cover",
          },
        },
        resize: {
          thumb: { width: 457, height: 655, maintain_ratio: true },
          large: { width: 700, height: 1003, maintain_ratio: true },
        },
      },
    },
    product: {
      cover: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "3072",
        min_width: 457,
        min_height: 655,
        pre_name: "pc-",
        sub_name: "",
        sub_folder: "product/cover",
        s3_bucket: "moa.images",
        time_rand: 4,
        servers: {
          sv1: {
            type: "aws",
            using: true,
            s3_key: "",
            s3_bucket: "",
            sub_folder: "product/cover",
          },
        },
        resize: {
          thumb: { width: 457, height: 655, maintain_ratio: true },
          large: { width: 700, height: 1003, maintain_ratio: true },
        },
      },
      barcode: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "3072",
        min_width: 457,
        min_height: 655,
        pre_name: "",
        sub_name: "",
        sub_folder: "product/barcode",
        s3_bucket: "moa.images",
        time_rand: 4,
        servers: {
          sv1: {
            type: "aws",
            using: true,
            s3_key: "", // s3 config key, if we have many aws s3 server
            s3_bucket: "",
            sub_folder: "product/barcode",
          },
        },
        resize: {
          thumb: { width: 457, height: 655, maintain_ratio: true },
          large: { width: 700, height: 1003, maintain_ratio: true },
        },
      },
      detail: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        min_width: 458,
        min_height: 655,
        pre_name: "pd-",
        sub_name: "",
        time_rand: 4,
        file_name: "pd-",
        servers: {
          s1: {
            type: "s3",
            used: true,
            s3_key: "", // s3 config key, if we have many aws s3 server
            s3_bucket: "",
            sub_folder: "product/detail",
          },
        },
        resize: {
          content: { width: 750, height: "", maintain_ratio: true },
        },
      },
    },
    review: {
      cover: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: 2048,
        max_width: "",
        max_height: "",
        min_width: 400,
        min_height: "",
        file_name: "rc-",
        time_rand: 4,
        sub_folder: "review/cover",
        s3_bucket: "moa.images",
      },
    },
    product_qna: {
      cover: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "3072",
        min_width: 457,
        min_height: 655,
        pre_name: "qa-",
        sub_name: "",
        time_rand: 4,
        sub_folder: "product_qna/cover",
      },
    },
    mart: {
      logo: {
        is_image: true,
        ratio: true,
        check_mime: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "",
        max_height: "",
        min_width: "",
        min_height: "",
        pre_name: "mr-",
        sub_name: "",
        sub_folder: "mart/logo",
        time_rand: 4,
        resize: {
          logo: { width: 300, height: "", maintain_ratio: true },
        },
      },
      logoapp: {
        is_image: true,
        ratio: true,
        check_mime: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "",
        max_height: "",
        min_width: "",
        min_height: "",
        pre_name: "mr-",
        sub_name: "",
        sub_folder: "mart/logoapp",
        time_rand: 4,
        resize: {
          logoapp: { width: 300, height: "", maintain_ratio: true },
        },
      },
      bannerapp: {
        is_image: true,
        ratio: true,
        check_mime: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "",
        max_height: "",
        min_width: "",
        min_height: "",
        pre_name: "mr-",
        sub_name: "",
        sub_folder: "mart/bannerapp",
        time_rand: 4,
        resize: {
          bannerapp: { width: 300, height: "", maintain_ratio: true },
        },
      },
    },
    notice: {
      cover: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "2048",
        max_height: "2048",
        file_name: "bl-",
        sub_folder: "notice/cover",
        s3_bucket: "moa.images",
      },
    },
    event: {
      cover: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "2048",
        max_height: "2048",
        file_name: "ec-",
        sub_folder: "event/cover",
        s3_bucket: "moa.images",
      },
      detail: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "2048",
        max_height: "2048",
        file_name: "ed-",
        sub_folder: "event/detail",
        s3_bucket: "moa.images",
      },
    },
    banner: {
      basic: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "10240",
        max_width: "5000",
        max_height: "5000",
        file_name: "b-",
        sub_folder: "banner/basic",
        s3_bucket: "moa.images",
      },
    },
    coupon: {
      image: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "2560",
        max_height: "800",
        file_name: "cp-",
        sub_folder: "coupon",
        s3_bucket: "moa.images",
      },
    },
    collection: {
      image: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "1500",
        max_height: "550",
        file_name: "c-",
        sub_folder: "collection",
      },
    },
    lookbook: {
      image: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "500",
        max_height: "700",
        file_name: "l-",
        sub_folder: "lookbook",
      },
    },
    my_qna: {
      cover: {
        is_image: true,
        ratio: true,
        check_mime: true,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "3072",
        max_width: "2048",
        max_height: "2048",
        pre_name: "mq-",
        sub_name: "",
        time_rand: 4,
        sub_folder: "qa/cover",
      },
    },
    store: {
      image: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "2048",
        max_width: "2560",
        max_height: "800",
        file_name: "s-",
        sub_folder: "store",
        s3_bucket: "moa.images",
      },
    },
    push_msg: {
      icon: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "200",
        max_width: "2560",
        max_height: "2560",
        file_name: "pi-",
        sub_folder: "push_msg/icon",
        s3_bucket: "moa.images",
      },
      detail: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "1024",
        max_width: "2560",
        max_height: "2560",
        file_name: "pd-",
        sub_folder: "push_msg/detail",
        s3_bucket: "moa.images",
      },
    },
    type_six: {
      icon: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "200",
        max_width: "2560",
        max_height: "2560",
        file_name: "ti-",
        sub_folder: "icon",
        s3_bucket: "moa.images",
      },
      detail: {
        is_image: true,
        ratio: false,
        watermark: false,
        allowed_types: "gif|png|jpg|jpeg",
        max_size: "1024",
        max_width: "2560",
        max_height: "2560",
        file_name: "td-",
        sub_folder: "detail",
        s3_bucket: "moa.images",
      },
    },
  },
};

module.exports = { configAws };
